version: "3.8"

services:
  app:
    container_name: wrthy_dev
    image: manromero/wrthy_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    ports:
      - 3000:3000